### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MCMic** [hagabaka/hib-dlagent#10]
I get this:

```
Searching for cogs-installer-build4
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/humblebundle/handlers.py", line 21, in parse_data
    return response.json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/hib-dlagent/discover-url.py", line 13, in <module>
    client.login(username, password)
  File "/usr/lib/python3.6/site-packages/humblebundle/decorators.py", line 20, in wrap
    result = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/humblebundle/client.py", line 115, in login
    return handlers.login_handler(self, response)
  File "/usr/lib/python3.6/site-packages/humblebundle/handlers.py", line 62, in login_handler
    data = parse_data(response)
  File "/usr/lib/python3.6/site-packages/humblebundle/handlers.py", line 23, in parse_data
    raise HumbleParseException("Invalid JSON: %s", str(e), request=response.request, response=response)
humblebundle.exceptions.HumbleParseException: [Errno Invalid JSON: %s] Extra data: line 1 column 5 (char 4)
```

**Comment by silverhook** [comment]
Sorry for bumping, but this problem still exists in 2020.
