### ISSUE TITLE
captcha prevents script from working

### ISSUE THREAD

**Issue by jose1711** [hagabaka/hib-dlagent#6]
Traceback (most recent call last):
  File "/usr/share/hib-dlagent/discover-url.py", line 12, in <module>
    client.login(username, password)
  File "/usr/lib/python3.4/site-packages/humblebundle/decorators.py", line 20, in wrap
    result = func(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/humblebundle/client.py", line 115, in login
    return handlers.login_handler(self, response)
  File "/usr/lib/python3.4/site-packages/humblebundle/handlers.py", line 76, in login_handler
    captcha_required=captcha_required, authy_required=authy_required)
humblebundle.exceptions.HumbleCaptchaException: Please answer the CAPTCHA

**Comment by hagabaka** [comment]
Captcha  is not supported and probably won't be, as the humblebundle-python library this tool uses doesn't process JavaScript. I think you are probably getting captchas because you used this tool too frequently (by HumbleBundle's standards) and maybe entered incorrect logins. I had this problem too when I was testing an older version of hib-dlagent, but not any more. I can only suggest waiting a day or two and trying again.
